### ISSUE TITLE
Cannot bring it to work 

### ISSUE THREAD

**Issue by Nomeasmo** [pascoual/meteor-pdfjs#2]
Meteor 0.9.4, Iron router 0.9.4

1) Try the example code with the `PDFJS.workerSrc = '/packages/pdfjs/build/pdf.worker.js';`
Error: `SyntaxError: Unexpected token '<'`
Since this file is not retrieved instead it returns my HTML
My .meteor folder does not have the above mentioned file in the assets folder 
2) Try the public `PDFJS.workerSrc = '/pdf.worker.js';`
The file is resolved but I get another error: `Error: Unknown action from worker: GetPageRequest`
3) Try the `PDFJS.disableWorker = true;`
It crashes with the following exception:
```
[Log] Warning: Setting up fake worker. (pascoual_pdfjs.js, line 232)
[Log] Warning: Unhandled rejection: TypeError: 'undefined' is not an object (evaluating 'PDFJS.WorkerMessageHandler.setup') (pascoual_pdfjs.js, line 232)
WorkerTransport_setupFakeWorker@http://localhost:3000/packages/pascoual_pdfjs.js?8964aa954a66c7631365859255e47d749415e251:4519:33
http://localhost:3000/packages/pascoual_pdfjs.js?8964aa954a66c7631365859255e47d749415e251:4474:27
[native code]
runHandlers@http://localhost:3000/packages/pascoual_pdfjs.js?8964aa954a66c7631365859255e47d749415e251:990:44
runHandlers@[native code]
```
Any idea?

**Comment by nhurwitz** [comment]
I'm getting this same issue. Any updates?

**Comment by partus** [comment]
replace '/packages/pdfjs/build/pdf.worker.js' with '/packages/pascoual_pdfjs/build/pdf.worker.js'
