### ISSUE TITLE
Only One Page

### ISSUE THREAD

**Issue by himadrighosh13** [pascoual/meteor-pdfjs#6]
I did as per given example. But Only Page is showing in the browser at a time. And the window is not like [demo](https://mozilla.github.io/pdf.js/web/viewer.html) given by pdf.js , it is like simple page showing image.

**Comment by pascoual** [comment]
It's PDFJS full package, you can do what you want with it.

I use it to show more than one page.
But it's your work to make the UI like you whant. You can take exemples from PDFJS.
