### ISSUE TITLE
Does not work as shown in DEMO example in Meteor

### ISSUE THREAD

**Issue by avishekgurung** [pascoual/meteor-pdfjs#7]
This package does not work as it is shown in the Hello World example of pdf js. It simply fetches the pdf and displays it like an image, only ONE page. 

Are we not supposed to get the view with all fancy buttons as shown in example?
Please let us know

**Comment by thsowers** [comment]
Bump. If this is the only functionality that this package provides, that is fine, but it should be more clearly specified

**Comment by pascoual** [comment]
It's PDFJS full package, you can do what you whant with it.

I use it to show more than one page.
But it's your work to make the UI like you whant. You can take exemples from PDFJS.
